Models/CustomerEntity.cs
using Microsoft.Azure.Cosmos.Table;
using Microsoft.Azure.Documents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class CustomerEntity : TableEntity
    {
        public CustomerEntity(string lastName, string firstName)
        {
            PartitionKey = lastName;
            RowKey = firstName;
        }

        public CustomerEntity() { }

        public string Email { get; set; }
        public string PhoneNumber { get; set; }
    }
}

Models/ProductEntity.cs
using Microsoft.Azure.Cosmos.Table;
using Microsoft.Azure.Documents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class ProductEntity : TableEntity
    {
        public ProductEntity(string category, string productName)
        {
            PartitionKey = category;
            RowKey = productName;
        }

        public ProductEntity() { }

        public string Description { get; set; }
        public double Price { get; set; }
    }
}

Controllers/CustomerController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.Azure.Cosmos.Table;
using WebApplication1.Models;


public class CustomerController : Controller
{
    private readonly AzureTableStorageRepository _repository = new AzureTableStorageRepository();

    public async Task<ActionResult> Index()
    {
        var table = await _repository.GetTableAsync("Customers");
        var query = new TableQuery<CustomerEntity>();
        var customers = new List<CustomerEntity>();

        TableContinuationToken token = null;
        do
        {
            var queryResult = await table.ExecuteQuerySegmentedAsync(query, token);
            customers.AddRange(queryResult.Results);
            token = queryResult.ContinuationToken;
        } while (token != null);

        return View(customers);
    }

    [HttpGet]
    public ActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(CustomerEntity customer)
    {
        var table = await _repository.GetTableAsync("Customers");
        await _repository.InsertOrMergeEntityAsync(table, customer);
        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<ActionResult> Delete(string partitionKey, string rowKey)
    {
        var table = await _repository.GetTableAsync("Customers");
        var retrieveResult = await _repository.RetrieveEntityAsync<CustomerEntity>(table, partitionKey, rowKey);
        if (retrieveResult.Result is CustomerEntity customer)
        {
            await _repository.DeleteEntityAsync(table, customer);
        }
        return RedirectToAction("Index");
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/ImagesController.cs
using System.Threading.Tasks;
using System.Web.Mvc;

public class ImagesController : Controller
{
    private readonly BlobService _blobService;

    public ImagesController()
    {
        var connectionString = System.Configuration.ConfigurationManager.ConnectionStrings["BlobStorageConnectionString"].ConnectionString;
        _blobService = new BlobService(connectionString);
    }

    // Action to display the list of images
    public async Task<ActionResult> Index()
    {
        var fileNames = await _blobService.ListBlobNamesAsync("media");
        return View(fileNames);
    }

    // Action to serve the image
    public async Task<ActionResult> ShowImage(string fileName)
    {
        var blob = await _blobService.GetBlobAsync("media", fileName);

        if (blob != null)
        {
            var stream = await blob.OpenReadAsync();
            var contentType = blob.Properties.ContentType;
            return File(stream, contentType);
        }

        return HttpNotFound();
    }

}

Controllers/MediaController.cs
using System.Threading.Tasks;
using System.Web.Mvc;

public class MediaController : Controller
{
    private readonly BlobService _blobService;

    public MediaController()
    {
        var connectionString = System.Configuration.ConfigurationManager.ConnectionStrings["BlobStorageConnectionString"].ConnectionString;
        _blobService = new BlobService(connectionString);
    }

    public async Task<ActionResult> ShowImage(string fileName)
    {
        var blobUrl = _blobService.GetBlobUrl("media", fileName);
        return Redirect(blobUrl); // Redirect to the blob URL
    }
}

Controllers/ProductController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.Azure.Cosmos.Table;
using WebApplication1.Models;


public class ProductController : Controller
{
    private readonly AzureTableStorageRepository _repository = new AzureTableStorageRepository();

    public async Task<ActionResult> Index()
    {
        var table = await _repository.GetTableAsync("Products");
        var query = new TableQuery<ProductEntity>();
        var products = new List<ProductEntity>();

        TableContinuationToken token = null;
        do
        {
            var queryResult = await table.ExecuteQuerySegmentedAsync(query, token);
            products.AddRange(queryResult.Results);
            token = queryResult.ContinuationToken;
        } while (token != null);

        return View(products);
    }

    [HttpGet]
    public ActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(ProductEntity product)
    {
        var table = await _repository.GetTableAsync("Products");
        await _repository.InsertOrMergeEntityAsync(table, product);
        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<ActionResult> Delete(string partitionKey, string rowKey)
    {
        var table = await _repository.GetTableAsync("Products");
        var retrieveResult = await _repository.RetrieveEntityAsync<ProductEntity>(table, partitionKey, rowKey);
        if (retrieveResult.Result is ProductEntity product)
        {
            await _repository.DeleteEntityAsync(table, product);
        }
        return RedirectToAction("Index");
    }
}

Views/Customer/Create.cshtml
@model WebApplication1.Models.CustomerEntity

@using (Html.BeginForm("Create", "Customer", FormMethod.Post))
{
    <div class="form-group">
        <label for="FirstName">First Name</label>
        <input type="text" class="form-control" id="FirstName" name="RowKey" required />
    </div>
    <div class="form-group">
        <label for="LastName">Last Name</label>
        <input type="text" class="form-control" id="LastName" name="PartitionKey" required />
    </div>
    <div class="form-group">
        <label for="Email">Email</label>
        <input type="email" class="form-control" id="Email" name="Email" required />
    </div>
    <div class="form-group">
        <label for="PhoneNumber">Phone Number</label>
        <input type="text" class="form-control" id="PhoneNumber" name="PhoneNumber" />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
}


Views/Customer/Index.cshtml
@model IEnumerable<WebApplication1.Models.CustomerEntity>


<h1>Customers</h1>
<table class="table">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var customer in Model)
        {
            <tr>
                <td>@customer.RowKey</td>
                <td>@customer.PartitionKey</td>
                <td>@customer.Email</td>
                <td>@customer.PhoneNumber</td>
                <td>
                    <!-- Edit Button -->
                    @Html.ActionLink("Edit", "Edit", new { id = customer.RowKey }, new { @class = "btn btn-primary btn-sm action-link" }) |

                    <!-- Details Button -->
                    @Html.ActionLink("Details", "Details", new { id = customer.RowKey }, new { @class = "btn btn-info btn-sm action-link" }) |

                    <!-- Delete Button (Form) -->
                    @using (Html.BeginForm("Delete", "Customer", new { partitionKey = customer.PartitionKey, rowKey = customer.RowKey }, FormMethod.Post, new { @class = "d-inline" }))
                    {
                        <button type="submit" class="btn btn-danger btn-sm action-link">Delete</button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<style>
    .action-link {
        margin-right: 5px;
    }

    .btn-edit {
        background-color: #007bff;
        color: white;
    }

    .btn-details {
        background-color: #17a2b8;
        color: white;
    }

    .btn-delete {
        background-color: #dc3545;
        color: white;
    }
</style>
@using (Html.BeginForm("Create", "Customer", FormMethod.Get))
{
    <button type="submit" class="btn btn-primary">Add New Customer</button>
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">Welcome to ABC Retail</h1>
        @*<p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>*@
    </section>

    @*<div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>*@
</main>
<style>
    h1{
        text-align:center
    }
</style>

Views/Images/Index.cshtml
@model IEnumerable<string>

<h2>Media Library</h2>

<ul class="image-list">
    @foreach (var fileName in Model)
    {
        <li class="image-item">
            <a href="@Url.Action("ShowImage", "Images", new { fileName = fileName })">
                <img src="@Url.Action("ShowImage", "Images", new { fileName = fileName })" alt="@fileName" />
            </a>
        </li>
    }
</ul>

<style>
    .image-list {
        list-style-type: none;
        padding: 0;
        margin: 0;
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 10px;
    }

    .image-item {
        border: 1px solid #ccc;
        padding: 5px;
        box-sizing: border-box;
        text-align: center; 
    }

        .image-item img {
            display: block;
            width: 50%; 
            height: auto;
            margin: auto;
        }
</style>

Views/Product/Create.cshtml
@model WebApplication1.Models.ProductEntity

@using (Html.BeginForm("Create", "Product", FormMethod.Post))
{
    <div class="form-group">
        <label for="ProductName">Product Name</label>
        <input type="text" class="form-control" id="ProductName" name="RowKey" required />
    </div>
    <div class="form-group">
        <label for="Category">Category</label>
        <input type="text" class="form-control" id="Category" name="PartitionKey" required />
    </div>
    <div class="form-group">
        <label for="Description">Description</label>
        <textarea class="form-control" id="Description" name="Description"></textarea>
    </div>
    <div class="form-group">
        <label for="Price">Price</label>
        <input type="number" class="form-control" id="Price" name="Price" step="0.01" required />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
}

Views/Product/Index.cshtml
@model IEnumerable<WebApplication1.Models.ProductEntity>


<h1>Products</h1>
<table class="table">
    <thead>
        <tr>
            <th>Product Name</th>
            <th>Category</th>
            <th>Description</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model)
        {
            <tr>
                <td>@product.RowKey</td>
                <td>@product.PartitionKey</td>
                <td>@product.Description</td>
                <td>R @product.Price.ToString("F2")</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = product.RowKey }, new { @class = "btn btn-primary btn-sm action-link" }) |
                    @Html.ActionLink("Details", "Details", new { id = product.RowKey }, new { @class = "btn btn-info btn-sm action-link" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = product.RowKey }, new { @class = "btn btn-danger btn-sm action-link" })
                </td>
            </tr>
        }
    </tbody>
</table>

<style>
    .action-link {
        margin-right: 5px;
    }

    .btn-edit {
        background-color: #007bff;
        color: white;
    }

    .btn-details {
        background-color: #17a2b8;
        color: white;
    }

    .btn-delete {
        background-color: #dc3545;
        color: white;
    }
</style>
@using (Html.BeginForm("Create", "Product", FormMethod.Get))
{
    <button type="submit" class="btn btn-primary">Add New Product</button>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @*<li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@
                    <li>@Html.ActionLink("Customers", "Index", "Customer", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Products", "Index", "Product", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Media", "Index", "Images", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ST10435769-Trevor Mohasoa</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
